import type {GetStaticPaths, GetStaticProps, NextPage} from 'next';
import Head from 'next/head';
import Link from 'next/link';
import Image from 'next/image';
import fs from 'fs';
import * as path from 'path';
import matter from 'gray-matter';
import {serialize} from 'next-mdx-remote/serialize';
import {MDXRemote} from 'next-mdx-remote';
import SyntaxHighlighter from 'react-syntax-highlighter';
import {ParsedUrlQuery} from 'querystring';
import Button from '../../components/Button';
import {arrowBack} from '../../assets/images/images';

export const getStaticPaths: GetStaticPaths = async () => {
  const files = fs.readdirSync(path.join('posts'));

  const paths = files.map(filename => {
    return {
      params: {
        slug: filename.replace('.mdx', ''),
      },
    };
  });

  return {
    paths,
    fallback: false,
  };
};

interface SlugProps extends ParsedUrlQuery {
  slug: string;
}

interface FrontMatter {
  title: string;
  date: string;
  time: string;
  thumbnailUrl: string;
}

interface Props {
  frontMatter: FrontMatter;
  mdxSource: object;
}

export const getStaticProps: GetStaticProps<
  Record<string, unknown>,
  SlugProps
> = async context => {
  const slug = context.params?.slug ?? '';
  const markdownWithMeta = fs.readFileSync(
    path.join('posts', slug + '.mdx'),
    'utf-8',
  );

  const {data: frontMatter, content} = matter(markdownWithMeta);

  const mdxSource = await serialize(content);

  return {
    props: {
      frontMatter,
      slug,
      mdxSource,
    },
  };
};

const components = {Button, SyntaxHighlighter};

const Post: NextPage<Props> = ({
  frontMatter: {title, date, time, thumbnailUrl},
  mdxSource,
}) => {
  return (
    <div>
      <Head>
        <title>{title}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="post">
        <Link href="/blog">
          <a className="flex items-center gap-3 mt-18">
            <Image alt="" src={arrowBack} />
            <span className="text-2md text-grey">Back to posts</span>
          </a>
        </Link>
        <div className="max-w-[848px] mt-[104px] mx-auto">
          <h1 className="text-xl">{title}</h1>
          <p className="mt-6 text-2md text-body font-medium">
            {date} - {time}
          </p>
        </div>
        <div className="my-14 w-full h-[576px] relative">
          <Image
            alt=""
            src={thumbnailUrl}
            layout="fill"
            objectFit="cover"
            objectPosition="center"
          />
        </div>
        <section className="max-w-[848px] mx-auto post-content">
          <MDXRemote
            compiledSource={''}
            {...mdxSource}
            components={components}
          />
        </section>
      </div>
    </div>
  );
};

export default Post;
