import Head from 'next/head';
import Image from 'next/image';
import Link from 'next/link';
import {NextPage} from 'next';
import {arrowLight, blogHero, postOne} from '../../assets/images/images';

const posts = [
  {
    slug: 'simple-ways-to-manage-state-in-react',
    date: 'June 9th, 2022',
    title: 'Simple ways to manage state in react',
    image: postOne,
    time: '5 min read',
  },
  {
    slug: 'post-two',
    date: 'June 9th, 2022',
    title: 'Second Post',
    image: postOne,
    time: '5 min read',
  },
  {
    slug: 'post-three',
    date: 'June 9th, 2022',
    title: 'Third Post',
    image: postOne,
    time: '5 min read',
  },
  {
    slug: 'post-four',
    date: 'June 9th, 2022',
    title: 'Fourth post',
    image: postOne,
    time: '5 min read',
  },
  {
    slug: 'post-five',
    date: 'June 9th, 2022',
    title: 'Fifth post',
    image: postOne,
    time: '5 min read',
  },
];

const [, ...otherPosts] = posts;

const Blog: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Dayo Awobeku's Blog</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="flex basis-full items-center flex-wrap md:flex-nowrap justify-between gap-4 lg:gap-8 mt-10 md:mt-20">
        <div className="md:basis-2/3 lg:basis-auto lg:max-w-lg">
          <h3 className="text-xl md:text-2xl lg:text-4xl text-grey dark:text-white mb-10">
            Learn web development and get to know more about me here.
          </h3>
        </div>
        <Image src={blogHero} alt="" width={506} height={387} priority />
      </div>

      <div className="mt-20 bg-white-700 rounded hover:border-grey">
        <Link href={`/blog/${posts[0].slug}`} passHref>
          <a className="flex items-center justify-between p-6 md:p-20">
            <div>
              <p className="font-medium text-md text-grey">Featured article</p>
              <h3 className="mt-6 md:mt-8 text-2lg md:text-xl md:leading-[56px] text-grey max-w-lg">
                {posts[0].title}
              </h3>
              <p className="mt-6 md:mt-8 font-medium text-body text-3md">
                {posts[0].date} - 5 min read
              </p>
              <div className="inline-flex items-center gap-4 mt-10 md:mt-16">
                <span className="font-medium text-4md text-grey">
                  Read full article
                </span>
                <Image alt="" src={arrowLight} width={48} height={48} />
              </div>
            </div>
            <div className="hidden md:block w-[342px] h-[401px] relative">
              <Image
                alt=""
                src={posts[0].image}
                layout="fill"
                objectFit="cover"
                priority
              />
            </div>
          </a>
        </Link>
      </div>
      <div className="mt-16 grid blog-grid sm:grid-cols-2 md:grid-cols-3 gap-y-16 gap-x-6">
        {otherPosts.map((post, i) => (
          <Link href={`/blog/${post.slug}`} key={i} passHref>
            <a>
              <Image
                alt=""
                src={postOne}
                width={373}
                height={458}
                title="something"
                className="rounded"
              />
              <p className="mt-8 font-medium text-body dark:text-white-400 text-3md">
                {post.date} - <span>{post.time}</span>
              </p>
              <h4 className="mt-4 text-lg font-medium text-grey dark:text-white-700">
                {post.title}
              </h4>
            </a>
          </Link>
        ))}
      </div>
    </div>
  );
};

export default Blog;
