import React, {useState, useEffect} from 'react';
import {GetStaticProps, NextPage} from 'next';
import Head from 'next/head';
import Image from 'next/image';
import Link from 'next/link';
import {useTheme} from 'next-themes';
import {useRouter} from 'next/router';
import {posts} from '../../data/posts';
import {getCloudinaryImages, mapImageResources} from '../../lib/cloudinary';
import {arrowLight, blogHero, blogHeroDark} from '../../assets/images/images';

export const getStaticProps: GetStaticProps = async () => {
  const results = await getCloudinaryImages();
  const images = mapImageResources(results.resources);

  return {
    props: {images},
  };
};

// eslint-disable-next-line @typescript-eslint/no-explicit-any
const Blog: NextPage<{images: any}> = ({images}) => {
  const {theme} = useTheme();

  const cloudinaryImages = images.map((image: unknown) => {
    return image;
  });

  const allPosts = posts.map((item, i) =>
    Object.assign({}, item, cloudinaryImages[i]),
  );

  const firstPost = allPosts.shift();

  const [mounted, setMounted] = useState(false);

  useEffect(() => {
    setMounted(true);
  }, []);

  const router = useRouter();
  if (router.isFallback) {
    return <h1>Loading...</h1>;
  }
  if (!mounted) return null;

  return (
    <div>
      <Head>
        <title>Dayo Awobeku's Blog</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="flex flex-wrap items-center justify-between gap-4 mt-10 basis-full md:flex-nowrap lg:gap-8 md:mt-20">
        <div className="md:basis-2/3 lg:basis-auto lg:max-w-lg">
          <h1 className="mb-10 text-xl md:text-2xl lg:text-4xl text-grey dark:text-white">
            Learn web development and get to know more about me here.
          </h1>
        </div>
        <Image
          src={theme === 'light' ? blogHero : blogHeroDark}
          alt=""
          width={506}
          height={387}
          priority
          placeholder="blur"
          blurDataURL="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8Xg8AAnMBeJQW2OIAAAAASUVORK5CYII="
        />
      </div>

      <div className="mt-20 transition-all duration-300 rounded outline-none bg-white-700 outline-[3px] outline-offset-4 hover:outline-info">
        <Link href={`/blog/${firstPost.slug}`}>
          <a className="flex items-center justify-between p-6 md:p-20 group">
            <article>
              <p className="font-medium text-md text-grey">Featured article</p>
              <h3 className="mt-6 md:mt-8 text-2lg md:text-xl md:leading-[56px] text-grey max-w-lg">
                {firstPost.postTitle}
              </h3>
              <p className="mt-6 font-medium md:mt-8 text-body text-3md">
                {firstPost.date} - 5 min read
              </p>
              <div className="inline-flex items-center gap-4 mt-10 md:mt-16">
                <span className="font-medium text-4md text-grey mb-1">
                  Read full article
                </span>
                <div className="transition-all duration-300 group-hover:translate-x-2 w-5 h-5">
                  <Image alt="" src={arrowLight} width={20} height={20} />
                </div>
              </div>
            </article>
            <div className="hidden md:block w-[342px] h-[401px] relative">
              <Image
                alt={firstPost.imageTitle}
                src={firstPost.url}
                layout="fill"
                objectFit="cover"
                priority
                placeholder="blur"
                blurDataURL="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8Xg8AAnMBeJQW2OIAAAAASUVORK5CYII="
              />
            </div>
          </a>
        </Link>
      </div>
      <div className="grid mt-16 blog-grid sm:grid-cols-2 md:grid-cols-3 gap-y-16 gap-x-6">
        {allPosts.map((post, i) => (
          <Link href={`/blog/${post.slug}`} key={i} passHref>
            <a className="transition-all duration-300 rounded outline-none outline-[3px] outline-offset-4 hover:outline-info">
              <Image
                alt={post.imageTitle}
                src={post.url}
                width={373}
                height={458}
                title={post.imageTitle}
                className="rounded"
                objectFit="cover"
                quality={100}
                placeholder="blur"
                blurDataURL="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8Xg8AAnMBeJQW2OIAAAAASUVORK5CYII="
              />
              <p className="mt-8 font-medium text-body dark:text-white-400 text-3md">
                {post.date} - <span>{post.time}</span>
              </p>
              <h4 className="mt-4 text-lg font-medium text-grey dark:text-white-700">
                {post.postTitle}
              </h4>
            </a>
          </Link>
        ))}
      </div>
    </div>
  );
};

export default Blog;
