import Head from 'next/head';
import Image from 'next/image';
import Link from 'next/link';
import {GetStaticProps, NextPage} from 'next';
import fs from 'fs';
import * as path from 'path';
import matter from 'gray-matter';
import {
  arrowLight,
  blogHero,
  postOne,
  search,
} from '../../assets/images/images';

export const getStaticProps: GetStaticProps = async () => {
  const files = fs.readdirSync(path.join('posts'));

  const posts = files.map(filename => {
    const markdownWithMeta = fs.readFileSync(
      path.join('posts', filename),
      'utf-8',
    );
    const {data: frontMatter} = matter(markdownWithMeta);

    return {
      frontMatter,
      slug: filename.split('.')[0],
    };
  });

  return {
    props: {
      posts,
    },
  };
};

interface FrontMatter {
  title: string;
  date: string;
  thumbnailUrl: string;
}

interface ResponseObject {
  slug: string;
  frontMatter: FrontMatter;
}

interface BlogProps {
  posts: Array<ResponseObject>;
}

const Blog: NextPage<BlogProps> = ({posts}) => {
  return (
    <div>
      <Head>
        <title>Dayo Awobeku's Blog</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="flex items-center justify-between gap-8 mt-20">
        <div className="max-w-lg">
          <h3 className="text-xl leading-[56px] text-grey mb-10">
            Learn web development and get to know more about me here.
          </h3>
          <label htmlFor="search" className="relative">
            <input
              type="search"
              name="search"
              placeholder="Search posts"
              className="max-w-full w-full text-md text-body sm:w-[473px] outline outline-1 outline-body h-18 rounded-[56px] pl-16 pr-8"
            />
            <div className="absolute w-6 h-6 -translate-y-1/2 left-6 top-1/2 aspect-auto">
              <Image src={search} alt="" width={24} height={24} />
            </div>
            <div className="absolute font-semibold -translate-y-1/2 right-8 top-1/2 text-2md text-body">
              11
            </div>
          </label>
        </div>
        <div className="w-[506px] h-[387px]">
          <Image src={blogHero} alt="" layout="responsive" priority />
        </div>
      </div>

      <div className="mt-32 bg-white-700">
        <Link href={`/blog/${posts[0].slug}`} passHref>
          <a className="flex items-center justify-between p-20 rounded-sm">
            <div>
              <p className="font-medium text-md text-grey">Featured article</p>
              <h3 className="mt-8 text-xl leading-[56px] text-grey max-w-lg">
                {posts[0].frontMatter.title}
              </h3>
              <p className="mt-8 font-medium text-body text-3md">
                {posts[0].frontMatter.date} - 5 min read
              </p>
              <div className="inline-flex items-center gap-4 mt-16">
                <span className="font-medium text-4md text-grey">
                  Read full article
                </span>
                <Image alt="" src={arrowLight} width={48} height={48} />
              </div>
            </div>
            <div className="w-[342px] h-[401px] relative">
              <Image
                alt=""
                src={posts[0].frontMatter.thumbnailUrl}
                layout="fill"
                objectFit="cover"
                priority
              />
            </div>
          </a>
        </Link>
      </div>
      <div className="mt-16 grid grid-cols-3 gap-y-16 gap-x-6">
        {posts.map((post, i) => (
          <Link href={`/blog/${post.slug}`} key={i} passHref>
            <a>
              <Image
                alt=""
                src={postOne}
                width={373}
                height={458}
                title="something"
              />
              <p className="mt-8 font-medium text-body text-3md">
                {post.frontMatter.date} <span>- 5 min read</span>
              </p>
              <h4 className="mt-6 text-lg font-medium text-grey">
                {post.frontMatter.title}
              </h4>
            </a>
          </Link>
        ))}
      </div>
    </div>
  );
};

export default Blog;
