import type {NextPage} from 'next';
import Head from 'next/head';

const Post: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Blog post title</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    </div>
  );
};

export default Post;
