import {useQuery} from '@tanstack/react-query';
import axios from 'axios';
import type {NextPage} from 'next';
import Head from 'next/head';
import Image from 'next/image';
import Link from 'next/link';

interface Track {
  title: string;
  artist: string;
  songUrl: string;
}

const About: NextPage = () => {
  const {data: spotifyTopTracks} = useSpotifyTopTracks();

  return (
    <div>
      <Head>
        <title>Dayo Awobeku - About me</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <section>
        <div className="flex flex-wrap items-stretch justify-between w-full gap-8 mt-20 lg:flex-nowrap">
          <div className="w-full md:w-[47.69%]">
            <Image
              src="https://res.cloudinary.com/dspbvhlt6/image/upload/v1664732973/website-images/dayo-about_k5zazt.png"
              width={557}
              height={662}
              alt="Dayo"
              placeholder="blur"
              blurDataURL="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8Xg8AAnMBeJQW2OIAAAAASUVORK5CYII="
              priority
            />
          </div>
          <div className="w-full lg:w-[49.32%] pt-18 -mt-18 about-text-container">
            <h1 className="font-medium text-md text-grey dark:text-white-700">
              Get to know Dayo...
            </h1>
            <p className="text-md leading-[31px] text-body dark:text-grey-600 mt-8">
              I'm a UX designer that specializes in usability and minimalism. I
              got my start in the world of health science as a medical
              laboratory scientist, and I like bringing together physical and
              digital space. Check out my portfolio to see some of my work! For
              business enquiries, you can contact me here.
            </p>
            <p className="text-md leading-[31px] text-body dark:text-grey-600 mt-8">
              I recently earned my certificate in UX Design, but I first started
              thinking like a UX designer after my final year as a medical
              student.
            </p>
            <p className="text-md leading-[31px] text-body dark:text-grey-600 mt-8">
              I've worked in different hospitals and diagnostic centres for a
              while and all I had thought about was how much of a benefit
              digital tools would be to both the patients and the medical
              personnel.
            </p>
            <p className="text-md leading-[31px] text-body dark:text-grey-600 mt-8">
              My job made me think about how people in general navigate physical
              and virtual space. I enjoyed thinking this way so much that it
              inspired me to get my certificate in UX Design.
            </p>
            <p className="text-md leading-[31px] text-body dark:text-grey-600 mt-8">
              When I'm not working, I'm on my PlayStation.
            </p>
          </div>
        </div>
      </section>

      <section className="mt-28">
        <h2 className="text-4md font-bold">Top Tracks</h2>
        <p className="mt-4 text-md text-grey-800 dark:text-white-400">
          Curious what I'm currently jamming to? Here's my top tracks on Spotify
          updated daily.
        </p>

        <div>
          <div className="mt-6 divide-y divide-grey-800 flex flex-col gap-4">
            {spotifyTopTracks?.tracks?.map((track: Track, index: number) => (
              <div key={index} className="flex flex-col pt-4">
                <div className="flex items-start gap-3">
                  <p className="text-[0.875rem] text-grey-400 font-bold mt-1">
                    {index + 1}
                  </p>
                  <div>
                    <Link href={track.songUrl}>
                      <a
                        className="text-grey-100 text-md font-medium"
                        target="_blank"
                      >
                        {track.title}
                      </a>
                    </Link>
                    <p className="text-base text-grey-400 dark:font-medium">
                      {track.artist}
                    </p>
                  </div>
                </div>
              </div>
            ))}
          </div>
        </div>
      </section>
    </div>
  );
};

export default About;

function useSpotifyTopTracks() {
  return useQuery(
    ['spotify-top-tracks'],
    () => axios.get('/api/spotify/top-tracks').then(res => res.data),
    {
      staleTime: 1000 * 60 * 60 * 24,
    },
  );
}
