import type {NextPage} from 'next';
import Head from 'next/head';
import {Input, Textarea} from '../components/Input';

const Contact: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Dayo Awobeku's Blog</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="flex items-start justify-between mt-24">
        <div>
          <h1 className="text-4xl text-grey">Get in touch</h1>
          <p className="mt-4 text-grey text-2md">By filling the contact form</p>
          <div className="mt-12">
            <div className="text-2md">
              <span className="text-body">Or: </span>
              <a
                href="mailto: dayoawobeku@gmail.com"
                className="font-medium underline underline-offset-2 text-grey"
              >
                dayoawobeku@gmail.com
              </a>
            </div>
            <div className="mt-6 text-2md">
              <span className="text-body">Or: </span>
              <a
                href="/"
                className="font-medium underline underline-offset-2 text-grey"
              >
                LinkedIn
              </a>
            </div>
            <div className="mt-6 text-2md">
              <span className="text-body">Or: </span>
              <a
                href="tel: +234-818-194-2332"
                className="font-medium underline underline-offset-2 text-grey"
              >
                +234-818-194-2332
              </a>
            </div>
          </div>
        </div>

        <form className="w-full max-w-xl">
          <Input id="name" label="Name" placeholder="Your name" />
          <Input
            id="email"
            label="Email"
            placeholder="person.doe@example.com"
            type="email"
            className="mt-10"
          />
          <Input
            id="subject"
            label="Subject"
            placeholder="No subject"
            className="mt-10"
          />
          <Textarea
            id="body"
            label="Body"
            placeholder="A clear and concise message works wonders."
            className="mt-10"
          />

          <button className="px-6 py-4 mt-16 text-white rounded-sm text-md bg-grey">
            Send message
          </button>
        </form>
      </div>
    </div>
  );
};

export default Contact;
