import type {NextPage} from 'next';
import Head from 'next/head';
import HeroSection from '../components/LandingPage/HeroSection';
import Projects from '../components/LandingPage/Projects';
import Testimonials from '../components/LandingPage/Testimonials';
import AboutMe from '../components/LandingPage/AboutMe';

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Dayo Awobeku's Personal Website</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <HeroSection />
      <Projects />
      <Testimonials />
      <AboutMe />
    </div>
  );
};

export default Home;
