import type {NextPage} from 'next';
import Head from 'next/head';
import HeroSection from '../components/LandingPage/HeroSection';
import Expertise from '../components/LandingPage/Expertise';
import Projects from '../components/LandingPage/Projects';

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Dayo Awobeku's Personal Website</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <HeroSection />
      <Expertise />
      <Projects />
      {/* <Testimonials />
      <AboutMe />
      <ContactMe /> 
      <Footer /> */}
    </div>
  );
};

export default Home;
